export const CHANGE_SEARCH_FIELD = '_CHANGE_SEARCH_FIELD_'

export const REQUEST_MONSTERS_PENDING = 'REQUEST_MONSTERS_PENDING'
export const REQUEST_MONSTERS_SUCCESS = 'REQUEST_MONSTERS_SUCCESS'
export const REQUEST_MONSTERS_FAIL = 'REQUEST_MONSTERS_FAIL'